### PR TITLE
Add ssh client and rsync to the drush image.

### PR DESCRIPTION
**Pull request by slashrsm**
Drush relies on them for database and file syncing, etc.

### CODE REVIEW

**Comment by zaporylie** [comment]
It seems like test are failing due to https://github.com/drush-ops/drush/issues/2185

**Comment by zaporylie** [comment]
Ok, I fixed issue with `master`. You can rebase your branch and add `openssh-client` & `rsync` to drush 8 as well.

**Comment by slashrsm** [comment]
Done.

**Comment by zaporylie** [comment]
Thanks!

**Pull request merged**
